sudo: required
language: generic
services:
        - docker

before_install:
        - docker build -t tejas/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true tejas/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
        app: "docker"
        env: "Docker-env-1"
        bucket_name: "elasticbeanstalk-us-east-2-814842048115"
        bucket_path: "docker"
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: "$AWS_SECRET_KEY"
