sudo: required
language: generic
services:
        - docker

before_install:
        - docker build -t tejas/docker-react -f dockerfile.dev .

script:
        - docker run -e CI=true tejas/docker-react npm run test -- --coverage
